// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    BaseLoader: typeof import('./src/components/UI/BaseLoader.vue')['default']
    BottomNavigation: typeof import('./src/components/UI/BottomNavigation.vue')['default']
    CreateDriver: typeof import('./src/components/registration/CreateDriver.vue')['default']
    CreateShift: typeof import('./src/components/modals/shifts/CreateShift.vue')['default']
    CreateVehicle: typeof import('./src/components/registration/CreateVehicle.vue')['default']
    FinishedShift: typeof import('./src/components/modals/shifts/FinishedShift.vue')['default']
    Map: typeof import('./src/components/map/Map.vue')['default']
    Modals: typeof import('./src/components/modals/Modals.vue')['default']
    OrderDetail: typeof import('./src/components/modals/orders/OrderDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/UI/TopBar.vue')['default']
  }
}

export {}
