export interface IOrder {
  addressFrom: string,
  addressTo: string,
  babyChair: boolean,
  location: string,
  client: {
    id: number, 
    name: string,
    phone: string, 
    createdAt: string | Date,
    updatedAt: string | Date,
  },
  clientID: number,
  createdAt: string,
  id: number,
  maxCountPassenger: number,
  operatorName: string,
  preOrderCost: number,
  status: "pending" | "accepted" | "process" | "finished",
  tariff: {
    id: number,
    type: string, 
    costPerKilometer: number,
    costOutOfCity: number,
    costBabyChair: number,
  },
  tariffID: number,
  timeOrder: null | string,
  transportationAnimals: boolean,
  updatedAt: string,
}